name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

# cancel in-progress runs that use the same workflow and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-new-branch:
    name: Create New Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create and push new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          NEW_BRANCH="auto/update-tables-${{ github.run_id }}"
          git checkout -b $NEW_BRANCH
          git push --set-upstream origin $NEW_BRANCH

  create-tables:
    needs: create-new-branch
    name: Create Tables - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          ref: auto/update-tables-${{ github.run_id }}

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.59.0
          cache: false

      - run: pixi run create-tables

      - name: Commit and push tables
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add -A
          git commit -m "Auto-create NGIO tables on ${{ matrix.os }}" || echo "No changes to commit"
          git push

  check-tables:
    name: Check Tables - ${{ matrix.os }}
    needs: create-tables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          ref: auto/update-tables-${{ github.run_id }}

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.59.0
          cache: false

      - run: pixi run check-tables
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add -A
          git commit -m "Auto-check NGIO tables on ${{ matrix.os }}" || echo "No changes to commit"
          git push

  finalize-and-pr:
    name: Finalize and Create PR
    needs: [check-tables]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: auto/update-tables-${{ github.run_id }}

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.59.0
          cache: false

      - name: Update README
        run: pixi run update-readme

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head auto/update-tables-${{ github.run_id }} \
            --title "Auto-update NGIO tables" \
            --body "This PR was automatically created to update the NGIO tables."
