name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

# cancel in-progress runs that use the same workflow and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-new-branch:
    name: Create New Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create and push new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          NEW_BRANCH="auto/update-tables-${{ github.ref }}"
          git checkout -b $NEW_BRANCH
          git push --set-upstream origin $NEW_BRANCH

  create-tables:
    name: Create Tables - Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: auto/update-tables-${{ github.ref }}

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.59.0
          cache: false
      - run: pixi run create-tables
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "CI: auto-commit changes"
            git push
          else
            echo "No changes to commit"
          fi

  check-tables-ubuntu:
    name: Check Tables - ubuntu-latest
    needs: create-tables
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: auto/update-tables-${{ github.ref }}

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.59.0
          cache: false
      - run: pixi run check-tables
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "CI: auto-commit changes"
            git push
          else
            echo "No changes to commit"
          fi
