name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Run every month on the first day at midnight
    - cron: "0 0 1 * *"

jobs:
  create-new-branch:
    name: Create New Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Create and push new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          NEW_BRANCH="auto/dev"
          git checkout -b $NEW_BRANCH
          git push --set-upstream origin $NEW_BRANCH
